version: '3.8'

services:
  instagram-bot:
    build: .
    container_name: instagram_comment_bot
    restart: unless-stopped
    volumes:
      # Log dosyalarını host'ta sakla
      - ./logs:/app/logs
      # Session dosyalarını sakla (tekrar giriş yapmamak için)
      - ./sessions:/app/sessions
    environment:
      - TZ=Europe/Istanbul
      - PYTHONUNBUFFERED=1
    # Bellek ve CPU limitleri
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "print('Bot running')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s